[workspace]
members = [
    "src/halo2_simple",
    "src/halo2_layout",
    "src/halo2_cost",
    "src/halo2_chips",
    "src/halo2_struct",
    "src/nova_minroot",
    "src/nova_sign",
    "src/supernova",
]
