[package]
name = "halo2_cost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
group = "0.13"
halo2_proofs = "0.3"
gumdrop = "0.8"
rand_core = "0.6"
